# Generated by Django 2.2.3 on 2019-10-22 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191022_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_owner_name',
            field=models.CharField(default='User1', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
