# Generated by Django 2.2.3 on 2019-10-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20191022_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_owner_id',
            new_name='comment_owner',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_owner_id',
            new_name='item_owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_owner_name',
        ),
    ]
