# Generated by Django 2.2.3 on 2019-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20191022_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.CharField(default='firma vietii', max_length=100),
            preserve_default=False,
        ),
    ]
